language: bash
services: docker

install:
  - git clone https://github.com/iPaya/iPaya-storage.git ~/iPaya-storage

script:
  - docker build -t "ipaya/ipaya-storage:latest" .

after_script:
  - docker images

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push ipaya/ipaya-storage:latest;
    fi
  - if [ "$TRAVIS_TAG" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker tag ipaya/ipaya-storage:latest ipaya/ipaya-storage:$TRAVIS_TAG;
      docker push ipaya/ipaya-storage:$TRAVIS_TAG;
    fi

# vim:set et ts=2 sw=2:
