#!/usr/bin/env php
<?php

use yii\helpers\ArrayHelper;

defined('APP_ROOT') or define('APP_ROOT', __DIR__);

require(APP_ROOT . '/vendor/autoload.php');
require(APP_ROOT . '/src/bootstrap.php');
require(APP_ROOT . '/vendor/yiisoft/yii2/Yii.php');
require(COMMON_PATH . '/bootstrap.php');
require(CONSOLE_PATH . '/bootstrap.php');

$config = ArrayHelper::merge(
    require(COMMON_PATH . '/config/main.php'),
    require(CONSOLE_PATH . '/config/main.php')
);


$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
